--- 
- hosts: all 
  become: yes 
  tasks: 
      
  - name: i want to install java 8 on ubuntu node 
    apt: 
            name: "{{myjavainstallforubuntu}}"
            state: present
    when: ansible_os_family=="Debian"


  - name: i want to install java 11 on redhat node 
    yum: 
            name: "{{myjavainstallforredhat}}"
            state: present
    when: ansible_os_family=="RedHat"
